Algoritmo "Exercício 06"
//  
//  

Var

VelocidadeKM: real
VelocidadeMS: real
EspacoP: real
TemP: real
Inicio
Escreval ("Informe a velocidade em KM/H:")
 leia (VelocidadeKM)
Escreval ("Informe o espaço a ser percorrido em KM:")
 leia (EspacoP)

VelocidadeMS <- (VelocidadeKM/3.6)
TemP <- EspacoP/VelocidadeKM

escreval ("O tempo a ser percorrido será de:" + , VelocidadeMS)
Escreval ("O tempo a ser percorrido será de:" , TemP)



fimalgoritmo
